apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ofbiz.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "ofbiz.name" . }}
    chart: {{ template "ofbiz.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "ofbiz.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "ofbiz.name" . }}
        release: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image}}:{{ .Values.imageTag}}"
          imagePullPolicy: {{default "IfNotPresent" .Values.ImagePullPolicy}}
          env:
          - name: OFFBIZ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "ofbiz.fullname" . }}
                key: offbiz-password
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

