apiVersion: apps/v1
kind: Deployment
metadata:
  name: ofbiz-operator
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ofbiz-operator
  template:
    metadata:
      labels:
        name: ofbiz-operator
    spec:
      serviceAccountName: ofbiz-operator
      containers:
        - name: ofbiz-operator
          # Replace this with the built image name
          image: yobitel/ofbiz-ope:16.11
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ofbiz-operator"
