apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ofbiz.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "ofbiz.name" . }}
    chart: {{ template "ofbiz.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.offbizPassword }}
  offbiz-password:  {{ .Values.offbizPassword | b64enc | quote }}
  {{ else }}
  offbiz-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}

