{{- if .Values.podDisruptionBudgetEnabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "mongodb.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
{{ toYaml .Values.podDisruptionBudget | indent 2 }}
{{- end }}
