apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-operator
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cassandra-operator
  template:
    metadata:
      labels:
        name: cassandra-operator
    spec:
      serviceAccountName: cassandra-operator
      containers:
        - name: cassandra-operator
          # Replace this with the built image name
          image: yobitel/cassandra-ope:3.11.6
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cassandra-operator"
