apiVersion: v1
kind: Secret
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: superset
  name: superset-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  superset-password: {{ randAlphaNum 10 | b64enc | quote }}

 
