apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: superset
  name: superset
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: superset
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: superset
    spec:
      containers:
      - env:
        - name: ADMIN_USERNAME
          value: yobi
        - name: GOOGLE_APPLICATION_CREDENTIALS
        - name: MYSQL_DATABASE
        - name: MYSQL_HOST
        - name: MYSQL_PASS
        - name: MYSQL_PORT
        - name: MYSQL_USER
        - name: REDIS_HOST
        - name: REDIS_PORT
        - name: SUPERSET_ENV
        - name: ADMIN_PWD
          valueFrom:
            secretKeyRef:
              name: superset-secret
              key: superset-password
        image: 'yobitel/superset:0.36.0'
        imagePullPolicy: "IfNotPresent"
        name: superset
        ports:
        - containerPort: 8088
        - containerPort: 5555
        resources: {}
        volumeMounts:
        - mountPath: /home/superset/config/
          name: superset-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: superset-claim0
        persistentVolumeClaim:
          claimName: superset-claim0

