apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-zeppelin
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "zeppelin.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: {{ template "zeppelin.name" . }}
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: zeppelin
          image: {{ .Values.zeppelin.image.repository }}:{{ .Values.zeppelin.image.tag }}
          imagePullPolicy: {{ .Values.zeppelin.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: web
          env:
            - name: ZEPPELIN_PORT
              value: "8080"
            - name: ZEPPELIN_JAVA_OPTS
              value: >-
                -Dspark.driver.memory={{ .Values.spark.driverMemory }}
                -Dspark.executor.memory={{ .Values.spark.executorMemory }}
{{- if .Values.hadoop.useConfigMap }}
            - name: MASTER
              value: "yarn"
            - name: SPARK_SUBMIT_OPTIONS
              value: >-
                --deploy-mode client
                --num-executors {{ .Values.spark.numExecutors }}
{{- end }}
          volumeMounts:
{{- if .Values.hadoop.useConfigMap }}
            - mountPath: {{ .Values.hadoop.configPath }}
              name: hadoop-config
{{- end }}
          resources:
{{ toYaml .Values.zeppelin.resources | indent 12 }} 
{{- if .Values.hadoop.useConfigMap }}
      volumes:
        - name: hadoop-config
          configMap:
            name: {{ .Values.hadoop.configMapName }}
{{- end }}          
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
