kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: solr-operator
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: solr-operator
roleRef:
  kind: Role
  name: solr-operator
  apiGroup: rbac.authorization.k8s.io
