apiVersion: apps/v1
kind: Deployment
metadata:
  name: kylin-operator
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kylin-operator
  template:
    metadata:
      labels:
        name: kylin-operator
    spec:
      serviceAccountName: kylin-operator
      containers:
        - name: kylin-operator
          # Replace this with the built image name
          image: yobitel/kylin-operator:4.0.0
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kylin-operator"
