apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: observiumservices.yobitel.org
spec:
  group: yobitel.org
  names:
    kind: ObserviumService
    listKind: ObserviumServiceList
    plural: observiumservices
    singular: observiumservice
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
