apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "kafka.fullname" . }}-0
  namespace: kafka
  labels:
  {{- include "kafka.broker.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "kafka.fullname" . }}-1
  namespace: kafka
  labels:
  {{- include "kafka.broker.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "kafka.fullname" . }}-2 
  namespace: kafka
  labels:
  {{- include "kafka.broker.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"


