apiVersion: apps/v1
kind: Deployment
metadata:
  name: hbase-operator
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hbase-operator
  template:
    metadata:
      labels:
        name: hbase-operator
    spec:
      serviceAccountName: hbase-operator
      containers:
        - name: hbase-operator
          # Replace this with the built image name
          image: yobitel/hbase-ope:2.3.1
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "hbase-operator"
