apiVersion: yobitel.org/v1alpha1
kind: HbaseService
metadata:
  name: example-hbaseservice
spec:
  # Default values copied from <project_dir>/helm-charts/hbase/values.yaml
  
  antiAffinity: soft
  conf:
    hadoopUserName: hdfs
    hbaseSite:
      hbase.rootdir: null
      hbase.zookeeper.quorum: null
  hbase:
    master:
      replicas: 1
      resources:
        limits:
          cpu: 1000m
          memory: 2048Mi
        requests:
          cpu: 10m
          memory: 256Mi
    regionServer:
      replicas: 1
      resources:
        limits:
          cpu: 1000m
          memory: 2048Mi
        requests:
          cpu: 10m
          memory: 256Mi
  hbaseVersion: 2.3.1
  hdfs:
    enabled: true
  hpa:
    enabled: true
  image:
    pullPolicy: IfNotPresent
    repository: yobitel/hbase
    tag: 2.3.1
  namespace: hbase
  persistence:
    accessMode: ReadWriteOnce
    enabled: true
    size: 300Gi
  podDisruptionBudget:
    maxUnavailable: 1
  podDisruptionBudgetEnabled: true
  podSecurityContext:
    fsGroup: 2000
    runAsUser: 2000
  prometheus:
    config:
      lowercaseOutputLabelNames: true
      lowercaseOutputName: true
      rules:
      - labels:
          namespace: $1
          region: $3
          table: $2
        name: HBase_metric_$4
        pattern: Hadoop<service=HBase, name=RegionServer, sub=Regions><>Namespace_([^\W_]+)_table_([^\W_]+)_region_([^\W_]+)_metric_(\w+)
      - labels:
          name: $2
          sub: $3
        name: hadoop_$1_$4
        pattern: Hadoop<service=(\w+), name=(\w+), sub=(\w+)><>([\w._]+)
      - pattern: .+
    enabled: true
    image: yobitel/jmx-exporter
    imageTag: 0.3.1
    port: 5556
    resources: {}
    thriftPort: 5557
  zookeeper:
    enabled: true
    replicaCount: 1
  
