apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-operator
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sonarqube-operator
  template:
    metadata:
      labels:
        name: sonarqube-operator
    spec:
      serviceAccountName: sonarqube-operator
      containers:
        - name: sonarqube-operator
          # Replace this with the built image name
          image: yobitel/sonarqube-ope:7.9.2
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "sonarqube-operator"
