kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: superset-operator
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: superset-operator
  namespace: {{ .Values.namespace }}
  # Replace this with the namespace the operator is deployed in.
roleRef:
  kind: ClusterRole
  name: superset-operator
  apiGroup: rbac.authorization.k8s.io
