apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: superset
  name: superset
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  ports:
  - name: "8088"
    port: 8088
    targetPort: 8088
  - name: "5555"
    port: 5555
    targetPort: 5555
  selector:
    io.kompose.service: superset
status:
  loadBalancer: {}
