# Default values for cacti.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: cacti

replicaCount: 1

productCode: "9t18jw267f6pjyeicgxtun5jb"


image: 453854455992.dkr.ecr.us-east-1.amazonaws.com/yobitel:v1
imagepullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


podSecurityContext: 
  fsGroup: 2000
  runAsUser: 2000

service:
  type: LoadBalancer
  port: 80

hpa:
  enabled: true

serviceAccountName: cacti

podDisruptionBudgetEnabled: true
podDisruptionBudget:
  maxUnavailable: 1

persistence:
  enabled: true
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 300Gi

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "1000m"
    #memory: "1Gi"
    memory: "128Mi"

nodeSelector: {}

tolerations: []

affinity: {}
