apiVersion: v1
appVersion: 3.11.6
description: Apache Cassandra is a free and open-source distributed database management
  system designed to handle large amounts of data across many commodity servers, providing
  high availability with no single point of failure.
name: cassandra
version: "1"
