apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-hadoop-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "fullname" . }}
data:
  core-site.xml: {{ quote (index .Values.hadoop "core-site.xml") }}
