apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: grafanaservices.yobitel.org
spec:
  group: yobitel.org
  names:
    kind: GrafanaService
    listKind: GrafanaServiceList
    plural: grafanaservices
    singular: grafanaservice
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
