apiVersion: v1
appVersion: 1.10.10
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: 8.6.4
description: Airflow is a platform to programmatically author, schedule and monitor
  workflows
home: https://airflow.apache.org/
icon: https://airflow.apache.org/_images/pin_large.png
keywords:
- workflow
- dag
maintainers:
- email: gaetan@xeberon.net
  name: gsemet
name: airflow
sources:
- https://airflow.apache.org/
version: 7.5.0
