apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: airflowservices.yobitel.org
spec:
  group: yobitel.org
  names:
    kind: AirflowService
    listKind: AirflowServiceList
    plural: airflowservices
    singular: airflowservice
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
