apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-operator
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: flink-operator
  template:
    metadata:
      labels:
        name: flink-operator
    spec:
      serviceAccountName: flink-operator
      containers:
        - name: flink-operator
          # Replace this with the built image name
          image: yobitel/flink-ope:1.11.1
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "flink-operator"
