{{- if .Values.podDisruptionBudgetEnabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
{{ toYaml .Values.podDisruptionBudget | indent 2 }}
{{- end }}
