kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flink-operator
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: flink-operator
  # Replace this with the namespace the operator is deployed in.
roleRef:
  kind: Role
  name: flink-operator
  apiGroup: rbac.authorization.k8s.io
