apiVersion: apps/v1
kind: Deployment
metadata:
  name: ignite-operator
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ignite-operator
  template:
    metadata:
      labels:
        name: ignite-operator
    spec:
      serviceAccountName: ignite-operator
      containers:
        - name: ignite-operator
          # Replace this with the built image name
          image: yobitel/ignite-ope:2.8.1
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ignite-operator"
