apiVersion: v1 
kind: Service
metadata:
  name: openemr-https
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  ports:
    - targetPort: 443
      port: 443
      nodePort: 30443
  selector:
    app: openemr
