apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: solrservices.yobitel.org
spec:
  group: yobitel.org
  names:
    kind: SolrService
    listKind: SolrServiceList
    plural: solrservices
    singular: solrservice
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
