apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: opencartservices.yobitel.org
spec:
  group: yobitel.org
  names:
    kind: OpencartService
    listKind: OpencartServiceList
    plural: opencartservices
    singular: opencartservice
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
