apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: orangehrm
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: openemr
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
