apiVersion: apps/v1
kind: Deployment
metadata:
  name: orangehrm-operator
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: orangehrm-operator
  template:
    metadata:
      labels:
        name: orangehrm-operator
    spec:
      serviceAccountName: orangehrm-operator
      containers:
        - name: orangehrm-operator
          # Replace this with the built image name
          image: yobitel/orangehrm-ope:4.6
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "orangehrm-operator"
