apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: orangehrm
  name: orangehrm
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: orangehrm
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: orangehrm
    spec:
      containers:
      - env:
        - name: MARIADB_HOST
          value: mariadb
        - name: MARIADB_PORT_NUMBER
          value: "3306"
        - name: ORANGEHRM_DATABASE_NAME
          value: orangehrm
        - name: ORANGEHRM_DATABASE_USER
          value: orangehrm
        image: yobitel/orangehrm:4.6
        imagePullPolicy: ""
        name: orangehrm
        resources:
          requests:
            cpu: "100m"
            memory: "500Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - mountPath: /yobi
          name: orangehrm-orangehrm-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: orangehrm-orangehrm-data
        persistentVolumeClaim:
          claimName: orangehrm-orangehrm-data

