apiVersion: v1
entries:
  superset:
  - apiVersion: v1
    appVersion: 0.36.0
    created: "2020-09-28T15:34:23.4912305+05:30"
    description: Apache Superset is a modern, enterprise-ready business intelligence
      web application
    digest: e76abd257ec300c3b2056a6855eee7cc65195c7b955c876d3572746ff7751d7a
    name: superset
    urls:
    - superset-1.tgz
    version: "1"
generated: "2020-09-28T15:34:23.431872908+05:30"
