apiVersion: yobitel.org/v1alpha1
kind: RstudioService
metadata:
  name: example-rstudioservice
spec:
  # Default values copied from <project_dir>/helm-charts/rstudio/values.yaml
  
  namespace: rstudio

replicaCount: 1

image:
  repository: yobitel/rstudio
  tag: 4.0.0
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

crd:
  install: true

rbac:
  create: true
  name: rstudio-opeartor

serviceAccount:
  create: true
  name: rstudio-operator

podSecurityContext: 
  fsGroup: 2000

securityContext: 
  
podDisruptionBudgetEnabled: true
podDisruptionBudget:
  maxUnavailable: 1

hpa:
  enabled: true
  
service:
  type: LoadBalancer
  port: 80

sidecars:
  enabled: true
  image: yobitel/k8s-sidecar:0.1.20
  imagePullPolicy: IfNotPresent
  resources: {}

ingress:
  enabled: false
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: ~
      paths:
        - /rstudio(/|$)(.*)
  tls: []
  
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 30Gi
  

resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
  
