{{- if .Files.Glob "files/*" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pytorch.fullname" . }}-files
  namespace: {{ .Values.namespace }}
  labels: {{- include "pytorch.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "files/*").AsConfig | indent 2 }}
{{ end }}
