{{- if eq .Values.metadataStorage.type "postgresql" -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ include "druid.name" . }}
    chart: {{ include "druid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ include "druid.name" . }}
type: Opaque
data:
  postgres_password: {{ .Values.postgres.password | b64enc | quote }}
{{- end -}}

