apiVersion: apps/v1
kind: Deployment
metadata:
  name: observium-operator
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: observium-operator
  template:
    metadata:
      labels:
        name: observium-operator
    spec:
      serviceAccountName: observium-operator
      containers:
        - name: observium-operator
          # Replace this with the built image name
          image: yobitel/observium-ope:1.0
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "observium-operator"
