apiVersion: yobitel.org/v1alpha1
kind: ObserviumService
metadata:
  name: example-observiumservice
spec:
  # Default values copied from <project_dir>/helm-charts/observium/values.yaml
namespace: observium  
replicaCount: 1

image: yobitel/observium
imageTag: "1.0"
imagepullPolicy: IfNotPresent
imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  runAsUser: 1000

mariadb:
  enable: true
   
hpa:
  enable: true

pdb:
  enable: true

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  requests:
    cpu: "100m"
    memory: "500Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"
  

nodeSelector: {}

tolerations: []

affinity: {}
