apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: hbaseservices.yobitel.org
spec:
  group: yobitel.org
  names:
    kind: HbaseService
    listKind: HbaseServiceList
    plural: hbaseservices
    singular: hbaseservice
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
