apiVersion: v1
kind: Service
metadata:
  name: {{ template "ofbiz.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "ofbiz.name" . }}
    chart: {{ template "ofbiz.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: {{ template "ofbiz.name" . }}
    release: {{ .Release.Name }}
