apiVersion: apps/v1
kind: Deployment
metadata:
  name: openemr-operator
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: openemr-operator
  template:
    metadata:
      labels:
        name: openemr-operator
    spec:
      serviceAccountName: openemr-operator
      containers:
        - name: openemr-operator
          # Replace this with the built image name
          image: yobitel/openemr-ope:6.0.0
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "openemr-operator"
