apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: opencart
  name: opencart
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: opencart
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: opencart
    spec:
      containers:
      - image: yobitel/opencart:3.0.3.6
        imagePullPolicy: ""
        name: opencart
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
        volumeMounts:
        - mountPath: /var/lib
          name: opencart-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: opencart-data
        persistentVolumeClaim:
          claimName: opencart-data
