apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: zeppelinservices.yobitel.org
spec:
  group: yobitel.org
  names:
    kind: ZeppelinService
    listKind: ZeppelinServiceList
    plural: zeppelinservices
    singular: zeppelinservice
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
