apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: zabbixservices.yobitel.org
spec:
  group: yobitel.org
  names:
    kind: ZabbixService
    listKind: ZabbixServiceList
    plural: zabbixservices
    singular: zabbixservice
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
