apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqlservices.yobitel.org
spec:
  group: yobitel.org
  names:
    kind: MysqlService
    listKind: MysqlServiceList
    plural: mysqlservices
    singular: mysqlservice
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
