apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-operator
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zabbix-operator
  template:
    metadata:
      labels:
        name: zabbix-operator
    spec:
      serviceAccountName: zabbix-operator
      containers:
        - name: zabbix-operator
          # Replace this with the built image name
          image: yobitel/zabbix-ope:4.4
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "zabbix-operator"
