affinity: {}
fullnameOverride: ""
hpa:
  enabled: true
image: openemr/openemr
imagePullSecrets: []
imageTag: 6.0.0
imagepullPolicy: IfNotPresent
mysql:
  enabled: true
nameOverride: ""
namespace: openemr
nodeSelector: {}
pdb:
  enabled: true
persistence:
  enabled: true
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 500Mi
tolerations: []
