{{- if .Values.podDisruptionBudgetEnabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "{{ template "consul.fullname" . }}-pdb"
  namespace: {{ .Values.namespace }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "consul.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      component: "{{ .Release.Name }}-{{ .Values.Component }}"
{{- end }}
