apiVersion: yobitel.org/v1alpha1
kind: OperatorService
metadata:
  name: example-operatorservice
spec:
  # Default values copied from <project_dir>/helm-charts/consul/values.yaml
  
  Component: consul
  ConsulConfig: []
  ConsulDnsPort: 8600
  DatacenterName: dc1
  DisableHostNodeId: false
  Domain: consul
  Gossip:
    Create: true
    Encrypt: true
  HttpPort: 8500
  Image: consul
  ImagePullPolicy: Always
  ImageTag: "1.8"
  Replicas: 3
  Resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  RpcPort: 8400
  SerflanPort: 8301
  SerflanUdpPort: 8301
  SerfwanPort: 8302
  SerfwanUdpPort: 8302
  ServerPort: 8300
  Storage: 1Gi
  acl:
    agentToken: ""
    enabled: false
    masterToken: ""
  additionalLabels: {}
  affinity: |
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchExpressions:
            - key: component
              operator: In
              values:
              - "{{ .Release.Name }}-{{ .Values.Component }}"
  forceIpv6: false
  hpa:
    enabled: true
  joinPeers: []
  joinWan: []
  namespace: consul
  nodeSelector: {}
  podAnnotations: {}
  podDisruptionBudget:
    maxUnavailable: 1
  podDisruptionBudgetEnabled: true
  priorityClassName: ""
  tolerations: []
  ui:
    enabled: true
  uiIngress:
    annotations: {}
    enabled: false
    hosts: []
    labels: {}
    path: /
    tls: []
  uiService:
    annotations: {}
    enabled: true
    type: LoadBalancer
  
