apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cassandraservices.example.org
spec:
  group: example.org
  names:
    kind: CassandraService
    listKind: CassandraServiceList
    plural: cassandraservices
    singular: cassandraservice
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
